# Generated by Django 5.2.6 on 2025-10-05 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comentario_bloqueado_comentario_padre'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='posts/')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='blog.post')),
            ],
        ),
    ]
